# this target will compile all the files
all: calc

calc: main.o readMatrix.o determinant.o
	g++ -std=c++0x main.o readMatrix.o determinant.o -o calc

main.0: main.cpp
	g++ -c main.cpp

readMatrix.o: readMatrix.cpp
	g++ -c readMatrix.cpp

determinant.o: determinant.cpp
	g++ -c determinant.cpp

clean:
	rm -rf *o Calc