# this target will compile all the files
all: calc

calc: main.o readMatrix.o determinant.o
	g++ -std=c++0x main.cpp readMatrix.cpp determinant.cpp -o calc

main.0: main.cpp
	g++ -std=c++0x main.cpp

readMatrix.o: readMatrix.cpp
	g++ -std=c++0x readMatrix.cpp

determinant.o: determinant.cpp
	g++ -std=c++0x determinant.cpp

clean:
	rm -rf *o Calc