# this target will compile all the files
all: Calc

Calc: main.o readMatrix.o determinant.o
	g++ -std=c++0x main.cpp readMatrix.cpp determinant.cpp -o Calc

main.0: main.cpp
	g++ -c main.cpp

readMatrix.o: readMatrix.cpp
	g++ -c readMatrix.cpp

determinant.o: determinant.cpp
	g++ -c determinant.cpp

clean:
	rm -rf *o Calc